title: CCTV Dealer & Distributor Theni | MasterSafetyTheni
description: >-
  N. Muthu Senthil Kumar a graduate in MBA and a man of vision started this
  mission of safety first in Theni district of Tamil Nadu in the year 2010.
template:
  repo: cctv-dealer-and-distributor-theni-or-mastersafetytheni-template
  name: cctv-dealer-and-distributor-theni-or-mastersafetytheni
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
